// <auto-generated />
using System;
using Code2Gether_Discord_Bot.WebApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Code2Gether_Discord_Bot.WebApi.Migrations
{
    [DbContext(typeof(DiscordBotDbContext))]
    [Migration("20201215030230_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SnowflakeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MemberProject", b =>
                {
                    b.Property<int>("MembersID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembersID", "ProjectsID");

                    b.HasIndex("ProjectsID");

                    b.ToTable("MemberProject");
                });

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.Project", b =>
                {
                    b.HasOne("Code2Gether_Discord_Bot.Library.Models.Member", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MemberProject", b =>
                {
                    b.HasOne("Code2Gether_Discord_Bot.Library.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code2Gether_Discord_Bot.Library.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
