// <auto-generated />
using Code2Gether_Discord_Bot.WebApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Code2Gether_Discord_Bot.WebApi.Migrations
{
    [DbContext(typeof(DiscordBotDbContext))]
    [Migration("20201130001048_ProjectMemberForeignKeys")]
    partial class ProjectMemberForeignKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.Member", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<ulong>("SnowflakeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_SNOWFLAKE");

                    b.HasKey("ID");

                    b.ToTable("MEMBER");
                });

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.Project", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_NAME");

                    b.HasKey("ID");

                    b.ToTable("PROJECT");
                });

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.ProjectMember", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_MEMBER_ID");

                    b.Property<long>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<long>("ProjectID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.HasKey("ID");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProjectID");

                    b.ToTable("PROJECT_MEMBER");
                });

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.ProjectMember", b =>
                {
                    b.HasOne("Code2Gether_Discord_Bot.Library.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code2Gether_Discord_Bot.Library.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
