// <auto-generated />
using Code2Gether_Discord_Bot.WebApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Code2Gether_Discord_Bot.WebApi.Migrations
{
    [DbContext(typeof(DiscordBotDbContext))]
    [Migration("20201209020346_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<ulong>("SnowflakeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_SNOWFLAKE");

                    b.HasKey("ID");

                    b.ToTable("MEMBER");
                });

            modelBuilder.Entity("Code2Gether_Discord_Bot.Library.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PROJECT_ID");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MEMBER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_NAME");

                    b.HasKey("ID");

                    b.ToTable("PROJECT");
                });

            modelBuilder.Entity("MemberProject", b =>
                {
                    b.Property<int>("MembersID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembersID", "ProjectsID");

                    b.HasIndex("ProjectsID");

                    b.ToTable("MemberProject");
                });

            modelBuilder.Entity("MemberProject", b =>
                {
                    b.HasOne("Code2Gether_Discord_Bot.Library.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code2Gether_Discord_Bot.Library.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
