name: CD

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build Configuration'
        required: true
        default: 'Release'
      output:
        description: 'Output directory'
        required: false
        default: 'artifacts'


jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Deploy - Publish
      run: dotnet publish -c "${{ github.event.inputs.configuration }}" -o "${{ github.event.inputs.output }}"
    - name: Deploy - Upload Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
          path: 
            "${{ github.event.inputs.output }}"
