name: CD

on:
  push:
    branches:
      - main

jobs:
  deployment:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    
    - name: Stop Discord Bot Service
      env:
        SUDOER:  ${{ secrets.SUDO_CD }}
      run: 
        echo "$SUDOER" | xargs sudo -S service code2gether-discord-bot stop
        echo "$SUDOER" | xargs sudo -S service code2gether-discord-bot-api stop
    
    - name: Publish
      run: dotnet publish -c "Release" -o "/home/ubuntu/Code2Gether-Discord-Bot/release"
      
    - name: Start Discord Bot service
      env:
        SUDOER:  ${{ secrets.SUDO_CD }}
      run:
        echo "$SUDOER" | xargs sudo -S service code2gether-discord-bot restart
        #echo "$SUDOER" | xargs sudo -S service code2gether-discord-bot-api restart
        
    - name: Clean Bash History
      continue-on-error: true
      run:
        cat /dev/null > ~/.bash_history && history -cw
